const digest=async file=>{const b=await file.arrayBuffer();const h=await crypto.subtle.digest("SHA-256",b);return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")};
class EmemApp extends HTMLElement{
connectedCallback(){this.render();this.bind()}
render(){this.innerHTML=`<div class="shell"><header><div class="brand">emem</div><div class="nav"><span>check an emem</span><span>protocol</span></div></header><main><section class="hero" id="hero"><h1 class="why">The world is shared.<br>Its memory should be too.</h1><p class="promise">External memory any AI can use and verify.</p><label class="drop" id="drop"><input id="file" type="file" multiple><div><strong>Drop anything</strong><span>or choose files · paste text or a link</span></div></label><div class="sources"><i>satellite</i><i>drone</i><i>image</i><i>PDF</i><i>record</i><i>data</i><i>text</i></div></section><section class="manifest" id="manifest"><div class="status" id="status">emem'ing…</div><div class="token"><small>external memory</small><code id="token"></code></div><div class="actions"><button class="primary" id="copy">Copy address</button><button id="reason">Use with ChatGPT</button><button id="verify">Verify</button><button id="again">emem something else</button></div><div class="provenance"><div class="prov"><b>source</b><p id="source">preserved</p></div><div class="prov"><b>maintained by</b><p>human · machine · agent ready</p></div><div class="prov"><b>world</b><p>referents can be attached without changing the source</p></div></div></section></main><footer><span>Send the address, not another copy.</span><span class="machine">human · machine · agent</span></footer></div>`}
}
bind(){const f=this.querySelector("#file"),d=this.querySelector("#drop");f.onchange=()=>this.emem(f.files);["dragenter","dragover"].forEach(e=>d.addEventListener(e,x=>{x.preventDefault();d.dataset.over="true"}));["dragleave","drop"].forEach(e=>d.addEventListener(e,x=>{x.preventDefault();d.dataset.over="false"}));d.addEventListener("drop",e=>this.emem(e.dataTransfer.files));document.addEventListener("paste",e=>{const text=e.clipboardData?.getData("text");if(text)this.ememText(text)});this.querySelector("#again").onclick=()=>this.reset()}
async emem(files){if(!files?.length)return;this.show();const hashes=[];for(const x of files)hashes.push(await digest(x));this.finish(hashes.join(""),files.length===1?files[0].name:`${files.length} sources`)}
async ememText(text){this.show();const data=new TextEncoder().encode(text);const h=await crypto.subtle.digest("SHA-256",data);this.finish([...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join(""),/^https?:/.test(text)?"link":"pasted text")}
show(){this.querySelector("#hero").style.display="none";this.querySelector("#manifest").dataset.show="true";this.querySelector("#status").textContent="emem'ing…"}
finish(hash,source){const t=`emem:bundle:sha256:${hash.slice(0,40)}`;this.querySelector("#token").textContent=t;this.querySelector("#source").textContent=source;this.querySelector("#status").textContent="emem'd ✓";this.querySelector("#copy").onclick=()=>navigator.clipboard?.writeText(t);this.querySelector("#reason").onclick=()=>navigator.clipboard?.writeText(`Use this external memory address as context and verify it before reasoning: ${t}`);this.querySelector("#verify").onclick=()=>alert("Prototype: local content address verified. Production resolver will verify emem receipts and underlying objects.") }
reset(){this.querySelector("#manifest").dataset.show="false";this.querySelector("#hero").style.display="block";this.querySelector("#file").value=""}
}customElements.define("emem-app",EmemApp);